version: '3.8'

services:
  hiit-analyzer:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./settings:/app/settings
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped